### ISSUE TITLE
Flask ext.script module not found

### ISSUE THREAD

**Issue by patrickjmcd** [nutechsoftware/alarmdecoder-webapp#46] opened 2018-07-18 18:12 UTC
When initializing the db with `sudo python manage.py initdb`, I get the error 

```Shell
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from flask.ext.script import Manager, Command
ImportError: No module named ext.script
```

The flask extensions have changed from using `flask.ext.script` to `flask_script` naming scheme.

**Comment by Segfaul198** [comment] 2018-07-24 17:07
This is causing problems for the docker image as well. If you use the image then attempt to update the webapp it breaks because of this issue.

**Comment by patrickjmcd** [comment] 2018-07-26 02:40
Crickets from the devs. Looks like we're going to have to do this ourselves.

**Comment by Segfaul198** [comment] 2018-07-27 13:49
I was looking at the code. Shouldn't be terrible to fix, though I'm no professional coder. I'll try to give it a shot this weekend.

**Comment by Segfaul198** [comment] 2018-08-01 16:51
Update. Unfortunately I have not had a chance to dig into the code at this time.

**Comment by patrickjmcd** [comment] 2018-08-01 18:43
I've been attempting to fix it as well, but it's not as simple as a find and replace.

**Comment by f34rdotcom** [comment] 2018-08-10 19:58
I tried to reproduce but no luck. I took my stock image and booted it on a the new Pi 3B+. I went into /opt/alarmdecoder-webapp and did a 'python manage.py initdb' I did not SUDO as the owners should all be pi:pi but to see if it did cause an issue I also did it with sudo. Only issue was an alchemy warning.

What do I need to do to reproduce this?

**Comment by weevis** [comment] 2018-08-12 00:00
This is due to a newer version of flask and flask_script.  Force a lower
version or fix the code to work with a newer version.

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by vperez** [comment] 2018-08-28 16:35
I published a pull request to fix this. Waiting for it to be approved.
https://github.com/nutechsoftware/alarmdecoder-webapp/pull/47

**Comment by f34rdotcom** [comment] 2019-01-13 01:31
This was merged. Thanks!

**Closed by f34rdotcom** 2019-01-13 01:31 UTC
